name: flutter_klarna_inapp_sdk
description: Klarna&#x27;s Flutter wrapper library for the native Klarna In-App SDK
version: 0.0.1
homepage: https://github.com/klarna/flutter-klarna-inapp-sdk

environment:
  sdk: ">=2.12.0 <3.0.0"
  # Flutter versions prior to 1.12 did not support the
  # flutter.plugin.platforms map.
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.2.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.klarna.inapp.sdk.flutter_klarna_inapp_sdk
        pluginClass: FlutterKlarnaInappSdk
      ios:
        pluginClass: FlutterKlarnaInappSdk

